// Generated by scripts/export-offline.sh from a running host. Do not edit.
export const WORLDS = [
 {
  "architect": "reference-heuristic@1",
  "generator": {
   "kind": "liminal-houses@1",
   "params": {
    "flowers": [
     "#ffe08a",
     "#ff9e7a",
     "#ffffff",
     "#ffb3d1"
    ],
    "fog": {
     "color": "#e8a697",
     "far": 120,
     "near": 22
    },
    "foliage": [
     "#ffc4d8",
     "#ffd9e6",
     "#f6a6c1",
     "#ffe3ef"
    ],
    "grass": {
     "base": "#5a7040",
     "density": 0.8,
     "height": 0.45,
     "tip": "#e8c47a"
    },
    "ground": "#5a6b3c",
    "hedge": "#4a6136",
    "hemi": {
     "ground": "#8a6a4a",
     "intensity": 1.6,
     "sky": "#d6c4ff"
    },
    "house": {
     "door": "#ffc87a",
     "roof": "#6a4c86",
     "trim": "#fff3e6",
     "wall": "#dcc6ea",
     "window": "#ffb35c"
    },
    "lamp": "#ffb35c",
    "motes": "#ffd6ae",
    "night": false,
    "path": "#f2d2bd",
    "places": {
     "arch": 0.1,
     "cave": 0.05,
     "house": 0.6,
     "tower": 0.25
    },
    "ponds": 0.15,
    "sky": {
     "bottom": "#f2a596",
     "horizon": "#ffb08a",
     "top": "#4c3f86"
    },
    "sun": {
     "azimuth": 2.4,
     "color": "#ffaa66",
     "elevation": 0.14,
     "intensity": 2.2
    },
    "terrain": {
     "amp": 3.4,
     "scale": 52
    },
    "trees": "blossom",
    "trunk": "#5b3f3a",
    "water": "#b39be0"
   }
  },
  "hub": true,
  "id": "dusk-orchard",
  "name": "Dusk Orchard",
  "portal_policy": {
   "allow_hosts": [],
   "allow_local": true,
   "max_per_room": 3,
   "mode": "open"
  },
  "seed": 231017085,
  "spawn": "0,0",
  "tagline": "Blossom streets at the golden minute before evening that never ends."
 },
 {
  "architect": "reference-heuristic@1",
  "generator": {
   "kind": "liminal-houses@1",
   "params": {
    "flowers": [
     "#eef4ff",
     "#c9e3d8",
     "#f6f0d0"
    ],
    "fog": {
     "color": "#d0ddda",
     "far": 68,
     "near": 6
    },
    "foliage": [
     "#244a3c",
     "#2f5d4a",
     "#1d3d32",
     "#36695a"
    ],
    "grass": {
     "base": "#244a3c",
     "density": 0.9,
     "height": 0.4,
     "tip": "#8bb096"
    },
    "ground": "#2f5446",
    "hedge": "#2a4d40",
    "hemi": {
     "ground": "#2f4a40",
     "intensity": 1.4,
     "sky": "#e8f2f4"
    },
    "house": {
     "door": "#9cc6d8",
     "roof": "#3e5460",
     "trim": "#ffffff",
     "wall": "#f5f5f0",
     "window": "#fff3d8"
    },
    "lamp": "#eaf4ff",
    "motes": "#ffffff",
    "night": false,
    "path": "#d9dcd4",
    "places": {
     "arch": 0.05,
     "cave": 0.3,
     "house": 0.45,
     "tower": 0.2
    },
    "ponds": 0.4,
    "sky": {
     "bottom": "#d3dfdb",
     "horizon": "#e2ebe8",
     "top": "#9fb6bd"
    },
    "sun": {
     "azimuth": 4.0,
     "color": "#f2f6ff",
     "elevation": 0.7,
     "intensity": 1.3
    },
    "terrain": {
     "amp": 7.0,
     "scale": 70
    },
    "trees": "pine",
    "trunk": "#4a3a30",
    "water": "#8db4ae"
   }
  },
  "hub": true,
  "id": "fog-pines",
  "name": "Fog Pines",
  "portal_policy": {
   "allow_hosts": [],
   "allow_local": true,
   "max_per_room": 3,
   "mode": "open"
  },
  "seed": 252285237,
  "spawn": "0,0",
  "tagline": "White houses under tall pines. The fog keeps every secret twenty metres away."
 },
 {
  "architect": "reference-heuristic@1",
  "generator": {
   "kind": "liminal-houses@1",
   "params": {
    "flowers": [
     "#7ef0ff",
     "#c39bff",
     "#fff3a8"
    ],
    "fog": {
     "color": "#18214a",
     "far": 95,
     "near": 14
    },
    "foliage": [
     "#6ff0ff",
     "#c39bff",
     "#ff9be0",
     "#9bffcf"
    ],
    "grass": {
     "base": "#0f2a24",
     "density": 0.9,
     "height": 0.5,
     "tip": "#3f8a76"
    },
    "ground": "#10291f",
    "hedge": "#163a33",
    "hemi": {
     "ground": "#1a3040",
     "intensity": 1.5,
     "sky": "#6a7ac8"
    },
    "house": {
     "door": "#ffd27a",
     "roof": "#2a3052",
     "trim": "#e6ecff",
     "wall": "#c3cbe6",
     "window": "#ffcd76"
    },
    "lamp": "#ffd27a",
    "motes": "#d8ff7a",
    "night": true,
    "path": "#3a4470",
    "places": {
     "arch": 0.15,
     "cave": 0.3,
     "house": 0.45,
     "tower": 0.1
    },
    "ponds": 0.3,
    "sky": {
     "bottom": "#141c40",
     "horizon": "#2b3b6e",
     "top": "#070b26"
    },
    "sun": {
     "azimuth": 1.2,
     "color": "#a8bbff",
     "elevation": 0.8,
     "intensity": 1.5
    },
    "terrain": {
     "amp": 4.2,
     "scale": 46
    },
    "trees": "mushroom",
    "trunk": "#d9e4ff",
    "water": "#2b4f96"
   }
  },
  "hub": true,
  "id": "moonlit-meadow",
  "name": "Moonlit Meadow",
  "portal_policy": {
   "allow_hosts": [],
   "allow_local": true,
   "max_per_room": 2,
   "mode": "allowlist"
  },
  "seed": 805769559,
  "spawn": "0,0",
  "tagline": "A night that stays. Glowing mushrooms, fireflies, and every window lit for you."
 },
 {
  "architect": "reference-heuristic@1",
  "generator": {
   "kind": "liminal-houses@1",
   "params": {
    "flowers": [
     "#ff9fb5",
     "#ffd1dc",
     "#ffffff"
    ],
    "fog": {
     "color": "#ffe2e9",
     "far": 230,
     "near": 40
    },
    "foliage": [
     "#5fb985",
     "#85d49c",
     "#4aa678"
    ],
    "grass": {
     "base": "#e3bfba",
     "density": 0.18,
     "height": 0.3,
     "tip": "#fff3ec"
    },
    "ground": "#f4d6d2",
    "hedge": "#efb8c2",
    "hemi": {
     "ground": "#f2c9c4",
     "intensity": 1.3,
     "sky": "#e6f6ff"
    },
    "house": {
     "door": "#78d6df",
     "roof": "#ffb3c3",
     "trim": "#fff6f8",
     "wall": "#ffffff",
     "window": "#e8fbff"
    },
    "lamp": "#ffffff",
    "motes": "#ffffff",
    "night": false,
    "path": "#ffffff",
    "places": {
     "arch": 0.4,
     "cave": 0.05,
     "house": 0.45,
     "tower": 0.1
    },
    "ponds": 0.5,
    "sky": {
     "bottom": "#ffe3ea",
     "horizon": "#ffe7ef",
     "top": "#7fcaff"
    },
    "sun": {
     "azimuth": 1.0,
     "color": "#ffffff",
     "elevation": 1.25,
     "intensity": 2.6
    },
    "terrain": {
     "amp": 0.5,
     "scale": 90
    },
    "trees": "palm",
    "trunk": "#c9a27f",
    "water": "#9ff0ee"
   }
  },
  "hub": true,
  "id": "salt-flat-noon",
  "name": "Salt Flat Noon",
  "portal_policy": {
   "allow_hosts": [],
   "allow_local": false,
   "max_per_room": 0,
   "mode": "closed"
  },
  "seed": 1511518631,
  "spawn": "0,0",
  "tagline": "Pink salt, white houses, palms and a mirage that never resolves. An island: no doors lead out."
 },
 {
  "architect": "reference-heuristic@1",
  "generator": {
   "kind": "liminal-houses@1",
   "params": {
    "flowers": [
     "#ff8fb1",
     "#ffd36e",
     "#ffffff",
     "#b78cff",
     "#ff9e6b"
    ],
    "fog": {
     "color": "#dcebd9",
     "far": 150,
     "near": 30
    },
    "foliage": [
     "#3e9b4f",
     "#5fbf5a",
     "#2f7d45",
     "#78c95e"
    ],
    "grass": {
     "base": "#2f7a32",
     "density": 1.0,
     "height": 0.55,
     "tip": "#b8e46c"
    },
    "ground": "#4a8a3c",
    "hedge": "#2f7a3d",
    "hemi": {
     "ground": "#4f7a3c",
     "intensity": 1.1,
     "sky": "#cfe9ff"
    },
    "house": {
     "door": "#f4b9c1",
     "roof": "#86b3a2",
     "trim": "#ffffff",
     "wall": "#e7efe4",
     "window": "#fff0c2"
    },
    "lamp": "#fff0c0",
    "motes": "#fffbe0",
    "night": false,
    "path": "#efe6d2",
    "places": {
     "arch": 0.12,
     "cave": 0.08,
     "house": 0.7,
     "tower": 0.1
    },
    "ponds": 0.25,
    "sky": {
     "bottom": "#dfeedd",
     "horizon": "#f3f0dc",
     "top": "#6fb9ec"
    },
    "sun": {
     "azimuth": 0.6,
     "color": "#fff1d2",
     "elevation": 0.9,
     "intensity": 2.4
    },
    "terrain": {
     "amp": 2.6,
     "scale": 64
    },
    "trees": "round",
    "trunk": "#7a5a43",
    "water": "#79d3cc"
   }
  },
  "hub": true,
  "id": "the-lush",
  "name": "The Lush",
  "portal_policy": {
   "allow_hosts": [],
   "allow_local": true,
   "max_per_room": 4,
   "mode": "open"
  },
  "seed": 492443617,
  "spawn": "0,0",
  "tagline": "An endless suburb, overgrown and kind. Every house is the same until you go inside."
 }
];
export const THEMES = [{"id": "poolrooms", "name": "Poolrooms", "tags": ["water", "light", "stone"]}, {"id": "moss-library", "name": "Moss Library", "tags": ["books", "plants", "cozy"]}, {"id": "cloud-nursery", "name": "Cloud Nursery", "tags": ["sky", "cozy", "light"]}, {"id": "sunset-terrarium", "name": "Sunset Terrarium", "tags": ["plants", "light", "stone"]}, {"id": "night-aquarium", "name": "Night Aquarium", "tags": ["water", "creatures", "neon"]}, {"id": "vapor-mall", "name": "Vapor Mall", "tags": ["neon", "plants", "art"]}, {"id": "tea-garden", "name": "Tea Garden", "tags": ["water", "plants", "stone"]}, {"id": "fern-cathedral", "name": "Fern Cathedral", "tags": ["plants", "stone", "light"]}, {"id": "arcade-after-hours", "name": "Arcade After Hours", "tags": ["neon", "music", "light"]}, {"id": "snowglobe-den", "name": "Snowglobe Den", "tags": ["snow", "cozy", "light"]}, {"id": "citrus-kitchen", "name": "Citrus Kitchen", "tags": ["plants", "light", "cozy"]}, {"id": "velvet-theatre", "name": "Velvet Theatre", "tags": ["music", "art", "cozy"]}];
export const TAGS = ["water", "plants", "light", "books", "art", "cozy", "sky", "creatures", "music", "stone", "snow", "neon"];
