#!/bin/sh
# Snapshot a running host's world manifests and themes for the client's
# built-in offline host (used when the page is served without a server).
# Usage: scripts/export-offline.sh [http://localhost:8080]
set -e
H=${1:-http://localhost:8080}
OUT=$(dirname "$0")/../client/src/offline-data.js
python3 - "$H" "$OUT" <<'PY'
import json, sys, urllib.request
h, out = sys.argv[1], sys.argv[2]
get = lambda p: json.load(urllib.request.urlopen(h + p))
worlds = [get('/api/worlds/' + w['id'])['manifest'] for w in get('/api/worlds')]
themes = get('/api/themes')
with open(out, 'w') as f:
    f.write('// Generated by scripts/export-offline.sh from a running host. Do not edit.\n')
    f.write('export const WORLDS = ' + json.dumps(worlds, indent=1) + ';\n')
    f.write('export const THEMES = ' + json.dumps(themes['themes']) + ';\n')
    f.write('export const TAGS = ' + json.dumps(themes['tags']) + ';\n')
PY
echo "wrote $OUT"
